(()=>{'use strict';
const online=location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1';
let context={sectionId:location.pathname.includes('electricidadTest')?'pract':'all',title:'Curso de electricidad'},messages=[],busy=false,controller=null,returnFocus=null,expanded=false,fontSize=18,thinking=null,modelSaving=false,modelsLoading=false,failed=null;
const shell=document.createElement('div');shell.id='study-tutor';shell.innerHTML=`<button class="study-tutor-launch" type="button" aria-controls="study-tutor-panel" aria-expanded="false"><span aria-hidden="true">✦</span> BoeBot <small>Resuelve tus dudas</small></button><section id="study-tutor-panel" class="study-tutor-panel" role="dialog" aria-labelledby="study-tutor-title" hidden><header class="study-tutor-head"><div><span class="study-tutor-eyebrow">Tu apoyo para estudiar</span><h2 id="study-tutor-title">BoeBot · Electricidad</h2></div><button class="study-tutor-close" type="button" aria-label="Cerrar BoeBot">×</button></header><div class="study-tutor-context"><span>Estás consultando</span><b id="study-tutor-context"></b></div><div id="study-tutor-messages" class="study-tutor-messages" aria-live="polite" aria-relevant="additions text"></div><div class="study-tutor-suggestions"><button type="button" data-prompt="Explica este tema con palabras sencillas y un ejemplo breve.">Explícamelo</button><button type="button" data-prompt="Propón un ejemplo de aplicación de este tema y explica el método paso a paso.">Paso a paso</button><button type="button" data-prompt="Hazme una pregunta breve sobre este tema sin decir todavía la respuesta. Espera mi intento para corregirme.">Ponme a prueba</button></div><form class="study-tutor-form"><label for="study-tutor-question">Tu duda</label><textarea id="study-tutor-question" rows="2" maxlength="800" placeholder="¿Qué no entiendes? Puedes incluir los datos de un ejercicio." required></textarea><div class="study-tutor-form-actions"><span id="study-tutor-status" role="status"></span><button type="submit">Enviar →</button></div></form><p class="study-tutor-disclaimer">Explicaciones generadas por IA a partir del curso. Comprueba los requisitos en las fuentes oficiales.</p></section>`;
document.body.append(shell);const $=s=>shell.querySelector(s),launch=$('.study-tutor-launch'),panel=$('.study-tutor-panel'),input=$('#study-tutor-question'),feed=$('#study-tutor-messages'),status=$('#study-tutor-status'),submit=$('[type=submit]');
input.setAttribute('aria-label','Tu duda');
const headActions=document.createElement('div');headActions.className='study-tutor-head-actions';
const expand=document.createElement('button');expand.type='button';expand.className='study-tutor-expand';expand.innerHTML='<span aria-hidden="true">⤢</span><span class="study-tutor-expand-label">Ampliar</span>';headActions.append(expand,$('.study-tutor-close'));$('.study-tutor-head').append(headActions);
const reading=document.createElement('div');reading.className='study-tutor-reading';reading.setAttribute('role','group');reading.setAttribute('aria-label','Tamaño del texto');reading.innerHTML='<span>Texto</span><button type="button" class="study-tutor-font-down" aria-label="Reducir tamaño del texto" title="Reducir tamaño del texto">A−</button><button type="button" class="study-tutor-font-up" aria-label="Aumentar tamaño del texto" title="Aumentar tamaño del texto">A+</button>';$('.study-tutor-context').append(reading);
const fontDown=$('.study-tutor-font-down'),fontUp=$('.study-tutor-font-up'),background=new Map();
const chatActions=document.createElement('div');chatActions.className='study-tutor-chat-actions';chatActions.setAttribute('role','group');chatActions.setAttribute('aria-label','Conversación');chatActions.innerHTML='<button type="button" class="study-tutor-new"><span aria-hidden="true">＋</span> Nuevo chat</button><button type="button" class="study-tutor-copy" hidden><span aria-hidden="true">⧉</span> Copiar conversación</button>';$('.study-tutor-context').after(chatActions);
const newChat=$('.study-tutor-new'),copyChat=$('.study-tutor-copy');let copying=false;
const resetDialog=document.createElement('dialog');resetDialog.className='study-tutor-reset';resetDialog.setAttribute('role','alertdialog');resetDialog.setAttribute('aria-labelledby','study-tutor-reset-title');resetDialog.setAttribute('aria-describedby','study-tutor-reset-help');resetDialog.innerHTML='<h2 id="study-tutor-reset-title">¿Empezar un nuevo chat?</h2><p id="study-tutor-reset-help">Se perderá el historial de la conversación actual y la pregunta que estés escribiendo. Si quieres guardarlo, cancela y copia la conversación antes.</p><form method="dialog"><button value="cancel" autofocus>Cancelar</button><button value="new">Borrar y empezar</button></form>';shell.append(resetDialog);
newChat.addEventListener('click',()=>{resetDialog.returnValue='';resetDialog.showModal()});
resetDialog.addEventListener('close',()=>{if(resetDialog.returnValue==='new'){controller?.abort();controller=null;busy=false;messages=[];input.value='';status.textContent='';input.disabled=false;$('.study-tutor-suggestions').inert=false;welcome();modelControls();input.focus()}});
copyChat.addEventListener('click',async()=>{if(busy||copying)return;const text=['BoeBot · Electricidad',context.title,...[...feed.querySelectorAll('.study-tutor-message.user,.study-tutor-message.assistant')].filter(article=>!article.dataset.intro).map(article=>[article.querySelector('b').textContent+':',article.querySelector('p').textContent,...[...article.querySelectorAll('.study-tutor-sources a')].map(link=>link.textContent+' — '+link.href)].join('\n'))].join('\n\n');copying=true;modelControls();try{try{await navigator.clipboard.writeText(text)}catch{const selection=document.createElement('textarea'),previous=document.activeElement;selection.value=text;selection.readOnly=true;selection.style.cssText='position:fixed;left:-9999px;top:0';panel.append(selection);selection.select();const copied=document.execCommand('copy');selection.remove();previous?.focus();if(!copied)throw Error('copy')}status.textContent='Conversación copiada.'}catch{status.textContent='No se ha podido copiar. Selecciona el texto de la conversación para copiarlo.'}finally{copying=false;modelControls()}});
function setFontSize(value){fontSize=Math.max(16,Math.min(24,value));shell.style.setProperty('--tutor-message-size',fontSize+'px');fontDown.disabled=fontSize===16;fontUp.disabled=fontSize===24;try{localStorage.setItem('electricidad-tutor-font',String(fontSize))}catch{}}
try{const saved=Number(localStorage.getItem('electricidad-tutor-font'));if([16,18,20,22,24].includes(saved))fontSize=saved}catch{}setFontSize(fontSize);
fontDown.addEventListener('click',()=>setFontSize(fontSize-2));fontUp.addEventListener('click',()=>setFontSize(fontSize+2));
function syncLayout(){const modal=expanded&&!panel.hidden;panel.classList.toggle('is-expanded',expanded);panel.setAttribute('aria-modal',String(modal));expand.setAttribute('aria-pressed',String(expanded));expand.setAttribute('aria-label',expanded?'Reducir BoeBot':'Ampliar BoeBot');expand.title=expanded?'Volver al chat pequeño':'Ampliar el chat';expand.firstElementChild.textContent=expanded?'⤡':'⤢';$('.study-tutor-expand-label').textContent=expanded?'Reducir':'Ampliar';if(modal){for(const element of document.body.children)if(element!==shell&&!background.has(element)){background.set(element,element.inert);element.inert=true}}else{for(const [element,inert]of background)element.inert=inert;background.clear()}}
expand.addEventListener('click',()=>{expanded=!expanded;syncLayout()});syncLayout();
const canSelectModel=document.querySelector('.account-strip[data-tutor-admin="true"]')!==null;
let modelSelect=null,modelStatus=null,modelRequest=0;
if(canSelectModel){const controls=document.createElement('div');controls.className='study-tutor-model';controls.innerHTML='<label for="study-tutor-model">Modelo de BoeBot</label><select id="study-tutor-model" aria-describedby="study-tutor-model-help" disabled><option value="">Cargando modelos…</option></select><small id="study-tutor-model-help">Solo Roberto · Se aplica también a Agente BOE.</small><span class="study-tutor-model-status" role="status"></span>';$('.study-tutor-context').after(controls);modelSelect=$('#study-tutor-model');modelStatus=$('.study-tutor-model-status');modelSelect.addEventListener('change',()=>saveModel())}
function modelControls(){if(modelSelect)modelSelect.disabled=busy||modelSaving||modelsLoading||!modelSelect.value;submit.disabled=busy||modelSaving;newChat.disabled=modelSaving||copying;copyChat.disabled=busy||copying;copyChat.hidden=!messages.some(message=>message.role==='assistant')}
function showModels(data){const models=Array.isArray(data.models)?data.models.filter(model=>['gpt','minimax'].includes(model.id)):[];modelSelect.replaceChildren();for(const model of models){const option=document.createElement('option');option.value=model.id;option.textContent=(typeof model.label==='string'?model.label:model.id)+(model.enabled===true?'':' · No disponible');option.disabled=model.enabled!==true;modelSelect.append(option)}modelSelect.value=models.find(model=>model.selected&&model.enabled)?.id||'';modelSelect.dataset.selected=modelSelect.value;modelControls()}
async function loadModels(){if(!canSelectModel||modelSaving)return;const request=++modelRequest;modelsLoading=true;modelControls();modelStatus.textContent='';try{const response=await fetch('/api/assistant/models',{cache:'no-store',signal:AbortSignal.timeout(12000)});const data=await response.json();if(request!==modelRequest)return;if(!response.ok)throw Error(response.status===401?'Vuelve a entrar en Mi cuenta.':data.error||'No se pueden cargar los modelos.');showModels(data)}catch(error){if(request!==modelRequest)return;modelStatus.textContent=error.name==='TimeoutError'?'No se pueden cargar los modelos. Cierra y abre BoeBot para reintentar.':error.message}finally{if(request===modelRequest){modelsLoading=false;modelControls()}}}
async function saveModel(){if(!canSelectModel||busy||modelSaving||modelsLoading)return;const previous=modelSelect.dataset.selected||'',chosen=modelSelect.value;modelSaving=true;modelControls();modelStatus.textContent='Guardando…';try{const response=await fetch('/api/assistant/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:chosen}),cache:'no-store',signal:AbortSignal.timeout(12000)});const data=await response.json();if(!response.ok)throw Error(data.error||'No se ha podido guardar el modelo.');showModels(data);modelStatus.textContent='Guardado. Se usará desde la siguiente consulta.'}catch(error){modelSelect.value=previous;modelStatus.textContent=error.name==='TimeoutError'?'No se ha confirmado el cambio. Cierra y abre BoeBot para comprobarlo.':error.message}finally{modelSaving=false;modelControls()}}
function sourceUrl(s){if(typeof s!=='string')return null;try{const u=new URL(s,location.origin);if(u.origin===location.origin&&u.pathname==='/electricidad/'&&/^#[a-z0-9-]+$/i.test(u.hash))return u.href;if(u.protocol==='https:'&&u.hostname==='www.boe.es')return u.href}catch{}return null}
function append(role,text,sources=[],model,intro=false){const article=document.createElement('article');article.className='study-tutor-message '+role;if(intro)article.dataset.intro='true';const label=document.createElement('b');label.textContent=role==='user'?'Tú':'BoeBot';article.append(label);const copy=document.createElement('p');copy.textContent=text;article.append(copy);if(Array.isArray(sources)&&sources.length){const links=document.createElement('div');links.className='study-tutor-sources';sources.slice(0,8).forEach((s,i)=>{const url=sourceUrl(s.officialUrl);if(!url)return;const a=document.createElement('a');a.href=url;a.textContent=`[${i+1}] ${s.kind==='course'?'Apuntes · ':''}${s.title||'Consultar fuente'}`;if(s.kind!=='course'){a.target='_blank';a.rel='noopener noreferrer'}else a.addEventListener('click',()=>close());links.append(a)});if(links.childElementCount){const references=document.createElement('details'),summary=document.createElement('summary');references.className='study-tutor-references';summary.textContent='Fuentes ('+links.childElementCount+')';references.append(summary,links);article.append(references)}}if(canSelectModel&&role==='assistant'&&typeof model==='string'){const used=document.createElement('small');used.className='study-tutor-used-model';used.textContent='Modelo utilizado: '+model;article.append(used)}feed.append(article);if(role==='assistant'&&!intro)requestAnimationFrame(()=>{if(article.isConnected)feed.scrollTop+=article.getBoundingClientRect().top-feed.getBoundingClientRect().top-parseFloat(getComputedStyle(feed).paddingTop)});else feed.scrollTop=feed.scrollHeight}
function stopThinking(){thinking?.remove();thinking=null;feed.setAttribute('aria-busy','false')}
function showFailure(question,error){const article=document.createElement('article');article.className='study-tutor-message study-tutor-error';article.setAttribute('role','alert');const title=document.createElement('b');title.textContent='Consulta interrumpida';const copy=document.createElement('p');copy.textContent=error.name==='AbortError'?'La consulta ha tardado demasiado. Tu pregunta está guardada; puedes reintentar.':error.name==='TypeError'?'Se ha cortado la conexión. Tu pregunta está guardada; puedes reintentar.':error.name==='SyntaxError'?'La respuesta no se ha podido leer. Tu pregunta está guardada; puedes reintentar.':error.message||'No se ha podido recibir la respuesta. Tu pregunta está guardada.';article.append(title,copy);if(error.httpStatus===401){const link=document.createElement('a');link.href='/electricidad/cuenta';link.className='study-tutor-retry';link.textContent='Entrar de nuevo';article.append(link)}failed={question,article,canRetry:!error.httpStatus||error.httpStatus>=500};submit.textContent=failed.canRetry?'Reintentar →':'Enviar →';feed.append(article);feed.scrollTop+=article.getBoundingClientRect().top-feed.getBoundingClientRect().top-parseFloat(getComputedStyle(feed).paddingTop)}
input.addEventListener('input',()=>{submit.textContent=failed?.canRetry&&input.value.trim()===failed.question?'Reintentar →':'Enviar →'});
function startThinking(){stopThinking();thinking=document.createElement('article');thinking.className='study-tutor-message study-tutor-thinking';thinking.innerHTML=`<div class="study-tutor-atom" aria-hidden="true"><span class="study-tutor-atom-halo"></span><span class="study-tutor-orbit study-tutor-orbit-one"><i></i></span><span class="study-tutor-orbit study-tutor-orbit-two"><i></i></span><span class="study-tutor-orbit study-tutor-orbit-three"><i></i></span><span class="study-tutor-atom-core"><svg viewBox="0 0 32 40" focusable="false"><path d="M19 1 4 23h11l-2 16L29 16H18z" fill="currentColor"/></svg></span><span class="study-tutor-atom-spark spark-one"></span><span class="study-tutor-atom-spark spark-two"></span><span class="study-tutor-atom-spark spark-three"></span></div><div class="study-tutor-thinking-copy"><strong>BoeBot está pensando<span class="study-tutor-thinking-dots" aria-hidden="true"><i></i><i></i><i></i></span></strong><p>Preparando tu explicación.</p></div>`;feed.setAttribute('aria-busy','true');feed.append(thinking);feed.scrollTop=feed.scrollHeight}
function welcome(){stopThinking();failed=null;submit.textContent='Enviar →';copyChat.hidden=true;feed.replaceChildren();append('assistant','Dime qué te cuesta entender. Puedo aclarar el concepto, resolver un ejemplo paso a paso o preguntarte para comprobar si lo has entendido.',[],undefined,true);$('#study-tutor-context').textContent=context.title}
function contextKey(value){return [value.sectionId,value.cardId||'',value.quizUid||'',Number.isInteger(value.quizIndex)?value.quizIndex:''].join(':')}
function setContext(next){if(!next?.sectionId)return;if(contextKey(next)===contextKey(context)){if(next.title)context.title=next.title;$('#study-tutor-context').textContent=context.title;return}controller?.abort();controller=null;busy=false;modelControls();input.disabled=false;$('.study-tutor-suggestions').inert=false;context={sectionId:next.sectionId,...(next.cardId?{cardId:next.cardId}:{}),title:next.title||'Curso de electricidad',...(typeof next.quizUid==='string'&&Number.isInteger(next.quizIndex)?{quizUid:next.quizUid,quizIndex:next.quizIndex}:{})};messages=[];input.value='';status.textContent='';welcome()}
function open(next){const current=window.ElectricidadStudyContext;if(current?.tutorDisabled)return;if(next)setContext({...next,...(typeof current?.quizUid==='string'&&Number.isInteger(current.quizIndex)?{quizUid:current.quizUid,quizIndex:current.quizIndex}:{})});else if(current?.sectionId)setContext(current);returnFocus=document.activeElement;panel.hidden=false;launch.setAttribute('aria-expanded','true');launch.hidden=true;syncLayout();void loadModels();input.focus()}
function close(){panel.hidden=true;launch.hidden=false;launch.setAttribute('aria-expanded','false');syncLayout();if(returnFocus instanceof HTMLElement&&returnFocus.isConnected)returnFocus.focus();else launch.focus()}
launch.addEventListener('click',()=>open());$('.study-tutor-close').addEventListener('click',close);shell.addEventListener('keydown',e=>{if(panel.hidden||resetDialog.open)return;if(e.key==='Escape'){e.preventDefault();close()}else if(e.key==='Tab'&&expanded){const controls=[...panel.querySelectorAll('button,textarea,select,a[href]')].filter(element=>!element.disabled&&element.offsetParent!==null);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
window.addEventListener('electricidad-context',e=>{const d=e.detail;if(d?.tutorDisabled){controller?.abort();controller=null;busy=false;stopThinking();status.textContent='';modelControls();input.disabled=false;$('.study-tutor-suggestions').inert=false;if(!panel.hidden)close();return}if(d?.sectionId)setContext(d)});
document.addEventListener('click',e=>{const b=e.target.closest('[data-tutor-card],[data-tutor-section],[data-tutor-open]');if(!b)return;const next={sectionId:b.dataset.tutorSection||'all',...(b.dataset.tutorCard?{cardId:b.dataset.tutorCard}:{}),title:b.dataset.tutorTitle||document.querySelector('#section-head h1')?.textContent||'Curso de electricidad'};open(next);if(b.dataset.tutorQuestion)input.value=b.dataset.tutorQuestion.slice(0,800)});
$('.study-tutor-suggestions').addEventListener('click',e=>{const b=e.target.closest('[data-prompt]');if(b&&!busy){input.value=b.dataset.prompt;input.focus()}});
$('.study-tutor-form').addEventListener('submit',async e=>{e.preventDefault();const question=input.value.trim();if(!question||busy||modelSaving||window.ElectricidadStudyContext?.tutorDisabled)return;if(!online){status.textContent='BoeBot necesita conexión e iniciar sesión en agenteboe.com.';return}if(failed){if(question===failed.question&&failed.article.previousElementSibling?.classList.contains('user'))failed.article.previousElementSibling.remove();failed.article.remove();failed=null}submit.textContent='Enviar →';busy=true;modelControls();input.disabled=true;$('.study-tutor-suggestions').inert=true;controller=new AbortController();const active=controller,consulted={...context},current={sectionId:context.sectionId,...(context.cardId?{cardId:context.cardId}:{})};status.textContent='BoeBot está preparando tu explicación…';append('user',question);startThinking();input.value='';const timer=setTimeout(()=>active.abort(),53000);
try{const response=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,history:messages.slice(-4).map(m=>({role:m.role,content:m.content.slice(0,1000)})),study:current}),cache:'no-store',signal:active.signal});const data=await response.json();if(!response.ok)throw Object.assign(Error(response.status===401?'Tu sesión ha caducado. Vuelve a entrar en Mi cuenta.':data.error||'No se ha podido responder. Inténtalo de nuevo.'),{httpStatus:response.status});if(typeof data.answer!=='string'||!data.answer.trim())throw Error('La respuesta no se ha podido leer. Inténtalo otra vez.');if(active!==controller)return;messages=[...messages,{role:'user',content:question},{role:'assistant',content:data.answer}].slice(-12);append('assistant',data.answer,data.sources,data.model);if(consulted.quizUid)window.dispatchEvent(new CustomEvent('electricidad-tutor-used',{detail:consulted}));status.textContent='';}
catch(error){if(active!==controller)return;stopThinking();status.textContent='';input.value=question;showFailure(question,error);}
finally{clearTimeout(timer);if(active!==controller)return;stopThinking();busy=false;modelControls();input.disabled=false;$('.study-tutor-suggestions').inert=false;if(!panel.hidden)input.focus()}});
if(window.ElectricidadStudyContext)setContext(window.ElectricidadStudyContext);welcome();window.ElectricidadTutor={open};
})();
